services:
  somanyfeeds-db:
    image: postgres:17.5
    container_name: somanyfeeds-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'secret'
    volumes:
      - ./databases/somanyfeeds_db/init_scripts:/docker-entrypoint-initdb.d
      - ./.docker_data/somanyfeeds_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      start_period: 1s
      start_interval: 1s

  wait:
    image: dokku/wait
    container_name: wait
    depends_on:
      somanyfeeds-db:
        condition: service_healthy
