[project]
name = "somanyfeeds-py"
version = "0.1.0"
requires-python = "~=3.13.3"
dependencies = [
    "fastapi>=0.115.12,<1.0",
    "uvicorn>=0.34.2,<1.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1,<1.0",
    "mypy>=1.15.0,<2.0",
    "ruff>=0.11.7,<1.0",
]

[tool.mypy]
strict = true

[tool.ruff]
line-length = 120