[project]
name = "somanyfeeds-py"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "mypy>=1.15.0",
    "ruff>=0.11.7",
]

[tool.mypy]
strict = true

[tool.ruff]
line-length = 120